//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jade_Dragon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnhPhongKhachSan
    {
        public long MaAnhPhong { get; set; }
        public string LinkAnhPhong { get; set; }
        public Nullable<long> MaPhong { get; set; }
        public Nullable<long> MaKhachSan { get; set; }
    
        public virtual KhachSan KhachSan { get; set; }
        public virtual PhongKhachSan PhongKhachSan { get; set; }
    }
}
