//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jade_Dragon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGiaKhachSan
    {
        public long MaDanhGia { get; set; }
        public Nullable<long> SoSao { get; set; }
        public Nullable<long> MaNguoiDung { get; set; }
        public Nullable<long> MaKhachSan { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NguoiDung NguoiDung1 { get; set; }
        public virtual KhachSan KhachSan { get; set; }
    }
}
