//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jade_Dragon.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class KhachSan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachSan()
        {
            this.AnhKhachSans = new HashSet<AnhKhachSan>();
            this.AnhPhongKhachSans = new HashSet<AnhPhongKhachSan>();
            this.BinhLuans = new HashSet<BinhLuan>();
            this.DanhGiaKhachSans = new HashSet<DanhGiaKhachSan>();
            this.HoaDons = new HashSet<HoaDon>();
            this.NguoiDungs = new HashSet<NguoiDung>();
            this.PhongChats = new HashSet<PhongChat>();
            this.PhongKhachSans = new HashSet<PhongKhachSan>();
            this.ThongKeDanhGias = new HashSet<ThongKeDanhGia>();
        }
        public long MaKhachSan { get; set; }
        public string TenKhachSan { get; set; }
        public Nullable<long> SoDienThoai { get; set; }
        public string Gmail { get; set; }
        public string DiaChi { get; set; }
        public string KinhDo { get; set; }
        public string ViDo { get; set; }
        public Nullable<long> Gia { get; set; }
        public Nullable<double> ThangDiem { get; set; }
        public Nullable<long> SoTang { get; set; }
        public Nullable<long> MaKhuVuc { get; set; }
        public Nullable<bool> TrangThaiKs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnhKhachSan> AnhKhachSans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnhPhongKhachSan> AnhPhongKhachSans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGiaKhachSan> DanhGiaKhachSans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual KhuVuc KhuVuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NguoiDung> NguoiDungs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhongChat> PhongChats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhongKhachSan> PhongKhachSans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongKeDanhGia> ThongKeDanhGias { get; set; }
    }
}
