//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jade_Dragon.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NguoiDung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguoiDung()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
            this.DanhGiaKhachSans = new HashSet<DanhGiaKhachSan>();
            this.DanhGiaKhachSans1 = new HashSet<DanhGiaKhachSan>();
            this.HoaDons = new HashSet<HoaDon>();
            this.TinNhanNguoiDungs = new HashSet<TinNhanNguoiDung>();
            this.TinNhanNguoiDungs1 = new HashSet<TinNhanNguoiDung>();
            this.TinNhanNhoms = new HashSet<TinNhanNhom>();
        }
    
        public long MaNguoiDung { get; set; }
        public string HoTen { get; set; }
        public Nullable<long> SoDienThoai { get; set; }
        public Nullable<long> CMND { get; set; }
        public string DiaChi { get; set; }
        public string Gmail { get; set; }
        public string Avt { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public Nullable<long> MaKhachSan { get; set; }
        public Nullable<long> MaPhanQuyen { get; set; }
        public string Code { get; set; }
        public Nullable<bool> DaXacMinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGiaKhachSan> DanhGiaKhachSans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGiaKhachSan> DanhGiaKhachSans1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual KhachSan KhachSan { get; set; }
        public virtual PhanQuyen PhanQuyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TinNhanNguoiDung> TinNhanNguoiDungs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TinNhanNguoiDung> TinNhanNguoiDungs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TinNhanNhom> TinNhanNhoms { get; set; }
    }
}
