//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jade_Dragon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinNhanNguoiDung
    {
        public string MaChatNguoiDung { get; set; }
        public Nullable<long> IdNguoiNhan { get; set; }
        public Nullable<long> IdNguoiGui { get; set; }
        public string NoiDungChat { get; set; }
        public Nullable<System.DateTime> NgayGuiChat { get; set; }
        public string LinkAnh { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NguoiDung NguoiDung1 { get; set; }
    }
}
