//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jade_Dragon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinNhanNhom
    {
        public string MaTinNhan { get; set; }
        public Nullable<long> MaNguoiDung { get; set; }
        public string NoiDungChat { get; set; }
        public string LinkAnh { get; set; }
        public Nullable<long> MaPhongChat { get; set; }
        public Nullable<System.DateTime> NgayGui { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual PhongChat PhongChat { get; set; }
    }
}
